### ISSUE TITLE
make dev/reset is clearing out all the docker images and all volumes!!

### ISSUE THREAD

**Issue by dineshk4tryzens** [Automattic/vip-gold#3]
The `make dev/reset` ideally would be expected to remove the docker images and volumes of the wordpress VIP docker compose files alone. But instead, it is clearing ALL docker images and ALL docker volumes. A developer accidentally or intentionally triggering this command (thinking it will only clear WP's images and volumes) will find the whole docker system in his or her development machine in disarray, without even a warning or confirmation, and would need to set them all up from scratch!!
Need to either put a prompt to confirm that user want to clear it or clear only the images and volumes of the docker compose files of Wordpress VIP setup.

**Comment by seanosh** [comment]
Hi!

I don't think that's quite how it works. If you look at the Docker's [docs](https://docs.docker.com/engine/reference/commandline/system_prune/) for `docker system prune`, it would only remove all images and volumes so destructively if `-a/--all` was specified - which it wasn't here.

Agreed though that while the intent is limited to this specific project, executing `docker system prune` (even without `-a/--all`) could have unintended consequences. I've removed the command via [ebdaba7](https://github.com/Automattic/vip-gold/commit/ebdaba7a336f91648cd1a80386f33d10a16061bf).
